"""Initial tables

Revision ID: f930fadd3c74
Revises: 
Create Date: 2024-04-14 17:58:03.000482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f930fadd3c74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='user id'),
    sa.Column('email', sa.String(), nullable=False, comment='user email'),
    sa.Column('password', sa.String(), nullable=False, comment='user password'),
    sa.Column('name', sa.String(), nullable=False, comment='user name'),
    sa.Column('last_name', sa.String(), nullable=False, comment='user last name'),
    sa.Column('age', sa.Integer(), nullable=False, comment='user age'),
    sa.Column('description', sa.String(), nullable=False, comment='user description'),
    sa.Column('date_joined', sa.DateTime(), nullable=True, comment='user date joined'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
